export const AGREGAR_PRODUCTO = "AGREGAR-PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR-PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR-PRODUCTO_ERROR";

export const COMENZAR_DESCARGA_PRODUCTOS = "COMENZAR_DESCARGA_PRODUCTOS";
export const DESCARGA_PRODUCTOS_EXITO = "DESCARGA_PRODUCTOS_EXITO";
export const DESCARGA_PRODUCTOS_ERROR = "DESCARGA_PRODUCTOS_ERROR";
